'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'

export async function createBoard(formData: FormData) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const name = (formData.get('name') as string) || 'Untitled Board'

  // Insert board — slug is auto-generated by the DB trigger when empty
  const { data: board, error } = await supabase
    .from('boards')
    .insert({ name, owner_id: user.id, slug: '' } as Record<string, unknown>)
    .select('id, slug')
    .single()

  if (error || !board) {
    throw new Error(`Failed to create board: ${error?.message}`)
  }

  // Add owner as board member
  await supabase.from('board_members').insert({
    board_id: board.id,
    user_id: user.id,
    role: 'owner',
  })

  redirect(`/board/${board.slug}`)
}

export async function deleteBoard(boardId: string) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  // Only owner can delete — RLS enforces this
  const { error } = await supabase.from('boards').delete().eq('id', boardId)

  if (error) {
    throw new Error(`Failed to delete board: ${error.message}`)
  }

  redirect('/dashboard')
}
